# Generated by Django 3.1.7 on 2021-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageFile',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(default=False, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
