# Generated by Django 3.1.7 on 2021-04-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_imagemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
